server {
    listen 80;
    server_name localhost;

    root /var/www/frontend/web;
    index index.php index.html;
    charset utf-8;
    client_max_body_size 1000M;
    
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|pdf|zip|rar)$ {
        try_files $uri =404;
        access_log off;
        expires 30d;
    }

    location ~ ^/(assets|upload)/.*\.php$ {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

server {
    listen 80;
    server_name admin.localhost;
    client_max_body_size 1000M;

    root /var/www/backend/web;
    index index.php index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|pdf|zip|rar)$ {
        try_files $uri =404;
        access_log off;
        expires 30d;
    }

    location ~ ^/(assets|upload)/.*\.php$ {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}